apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-user-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: service-user
    spec:
      containers:
        - name: service-user
          image: registry.cn-shanghai.aliyuncs.com/nocoolming/service-user:2.1
          imagePullPolicy: Always
          ports:
            - containerPort: 7111
---
apiVersion: v1
kind: Service
metadata:
  name: service-user
spec:
  selector:
    app: service-user
  ports:
    - protocol: TCP
      port: 7111
      targetPort: 7111
