spring:
  application:
    name: userservice

server:
  port: 7111

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8763/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eurekaserver:8763/eureka/