spring:
  application:
    name: UserService

server:
  port: 7111

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8763/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}