spring:
  application:
    name: user-service

server:
  port: 7111

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8763/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.cloud.client.ip-address}:${server.port}
